## Dog Breed Classification

In this project we will use traditional CNN, CNN with data augmentation and finally transfer Learning by VGG16 model with weights pre-trained on Imagenet to solve the dog breed classification problem

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


### Load Dataset Files

In [0]:
import pandas as pd
import numpy as np

In [0]:
project_path1 = ('/content/gdrive/My Drive/Colab Notebooks/testjp.zip')

Now, upload the given dataset file shared with you in your google drive and give its path for the below given `project_path` variable. For example, a path is given below according to the file path in our google drive. You need to change this to match the path of yours.

In [0]:
project_path=("/content/gdrive/My Drive/Colab Notebooks/trainjp.zip")

Run the below code to extract all the images in the train.zip files given in the dataset. We are going to use these images as train and validation sets and their labels in further steps.

In [0]:
from zipfile import ZipFile
with ZipFile(project_path,'r') as z:
  z.extractall()

Repeat the same step for test.zip

In [0]:
from zipfile import ZipFile
with ZipFile(project_path1, 'r') as z:
  z.extractall()

Repeat the same step for sample_submission.csv.zip

In [0]:
from zipfile import ZipFile
with ZipFile('sample_submission.csv.zip', 'r') as z:
  z.extractall()

Repeat the same step for labels.csv.zip

In [0]:
from zipfile import ZipFile
with ZipFile('labels.csv.zip', 'r') as z:
  z.extractall()

After this process, we will have 4 files - Train folder, test folder and labels.csv and sample_submission.csv as part of your google drive

### Read labels.csv file using pandas

In [0]:
import pandas as pd
import numpy as np

In [0]:
labels=pd.read_csv('labels.csv')

### Print the count of each category of Dogs given in the dataset



In [5]:
labels.nunique()

id       10222
breed      120
dtype: int64

In [6]:
labels.head(5)

id             breed
0  000bec180eb18c7604dcecc8fe0dba07       boston_bull
1  001513dfcb2ffafc82cccf4d8bbaba97             dingo
2  001cdf01b096e06d78e9e5112d419397          pekinese
3  00214f311d5d2247d5dfe4fe24b2303d          bluetick
4  0021f9ceb3235effd7fcde7f7538ed62  golden_retriever

In [0]:
p= labels['breed'].value_counts()

In [8]:
print('category of Dogs', p)

category of Dogs scottish_deerhound      126
maltese_dog             117
afghan_hound            116
entlebucher             115
bernese_mountain_dog    114
                       ... 
golden_retriever         67
brabancon_griffon        67
komondor                 67
briard                   66
eskimo_dog               66
Name: breed, Length: 120, dtype: int64


### Get one-hot encodings of labels

In [0]:
onehot=pd.get_dummies(labels['breed'])

In [0]:
df = pd.concat([labels,pd.get_dummies(labels['breed'])],axis=1)

In [0]:
df.drop(['breed'],axis=1, inplace=True)

In [12]:
df.head()

id  ...  yorkshire_terrier
0  000bec180eb18c7604dcecc8fe0dba07  ...                  0
1  001513dfcb2ffafc82cccf4d8bbaba97  ...                  0
2  001cdf01b096e06d78e9e5112d419397  ...                  0
3  00214f311d5d2247d5dfe4fe24b2303d  ...                  0
4  0021f9ceb3235effd7fcde7f7538ed62  ...                  0

[5 rows x 121 columns]

## Preparing training dataset
1. Write a code which reads each and every id from labels.csv file and loads the corresponding image (in RGB - 128, 128, 3) from the train folder. <br>
2. Create 2 variables <br> 
     a.  x_train - Should have all the images of the dogs from train folder <br>
     b.  y_train - Corresponding label of the dog <br>
<u>Note:</u> The id of the dog images and its corresponding labels are available in labels.csv file   
<u>Hint:</u> Watch the video shared on "Preparing the training dataset" if you face issue on creating the training dataset

In [13]:
import os

import warnings
warnings.filterwarnings("ignore")

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

import xml.etree.ElementTree as ET

import numpy as np
import pandas as pd

from skimage.io import imread
from skimage.transform import resize
from PIL import Image
from imgaug import augmenters as iaa

from sklearn.model_selection import train_test_split

from keras.models import *
from keras.layers import *
from keras.optimizers import *
from keras.utils import *
from keras.callbacks import *

from keras.applications.densenet import DenseNet121, preprocess_input

Using TensorFlow backend.


In [0]:
img_file='/content/train/'

In [26]:
df1=df.assign(img_path=lambda x: img_file + x['id'] +'.jpg')
df1.head()

id  ...                                           img_path
0  000bec180eb18c7604dcecc8fe0dba07  ...  /content/train/000bec180eb18c7604dcecc8fe0dba0...
1  001513dfcb2ffafc82cccf4d8bbaba97  ...  /content/train/001513dfcb2ffafc82cccf4d8bbaba9...
2  001cdf01b096e06d78e9e5112d419397  ...  /content/train/001cdf01b096e06d78e9e5112d41939...
3  00214f311d5d2247d5dfe4fe24b2303d  ...  /content/train/00214f311d5d2247d5dfe4fe24b2303...
4  0021f9ceb3235effd7fcde7f7538ed62  ...  /content/train/0021f9ceb3235effd7fcde7f7538ed6...

[5 rows x 122 columns]

In [0]:
from keras.preprocessing.image import img_to_array,load_img,ImageDataGenerator
from keras.utils import to_categorical
import numpy as np



In [0]:
X_train=img_file


In [0]:
target=df1.iloc[:,1:120]

In [0]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

import cv2
im_size=100
enc = OneHotEncoder(handle_unknown='ignore')
data = enc.fit_transform(labels).toarray() 
target=pd.Series(labels['breed'])
one_hot=pd.get_dummies(target,sparse=True)
target=np.asarray(one_hot)

In [0]:
import cv2
im_size=100
ids=labels['id']
X_train=[]
y_train=target
for id in ids:
  img=cv2.imread('./train/{}'.format(id)+'.jpg')
  X_train.append(cv2.resize(img,(im_size,im_size)))
X_train=np.array(X_train,np.float32)

Normalize the training data and convert into 4 dimensions so that it can be used as an input to conv layers in the model

In [0]:
def standardize(array):
  array/=255
  return array
X_train=standardize(X_train)

### Split the training and validation data from `x_train_data` and `y_train_data` obtained from above step

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_train,y_train,test_size=0.2)

### Loading the test data
Read the id column from the samples_submission.csv and store it in test_img

In [0]:
ss=pd.read_csv('/content/sample_submission.csv')

In [48]:
ss.head(5)

id  ...  yorkshire_terrier
0  000621fb3cbb32d8935728e48679680e  ...           0.008333
1  00102ee9d8eb90812350685311fe5890  ...           0.008333
2  0012a730dfa437f5f3613fb75efcd4ce  ...           0.008333
3  001510bc8570bbeee98c8d80c8a95ec1  ...           0.008333
4  001a5f3114548acdefa3d4da05474c2e  ...           0.008333

[5 rows x 121 columns]

In [0]:
test_img=ss['id']

Run the below code to load the test image files in x_test_feature

Normalize the test data and convert it into 4 dimensions

In [0]:
test_file='/content/test'

In [0]:
#X_test=test_file

In [0]:
def standardize(array):
  array/=255
  return array
X_test=standardize(X_test)

### Build a basic conv neural network with 2 conv layers (kernel sizes - 5 and 3) add layers as mentioned below for classification.

1. Add a Dense layer with 256 neurons with `relu` activation

2. Add a Dense layer with 120 neurons as final layer (as there are 120 classes in the given dataset) with `softmax` activation for classifiaction. 

In [68]:
num_classes=120


from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.optimizers import Adam

print(X_train.shape,y_train.shape,X_test.shape)

(8177, 100, 100, 3) (8177, 120) (2045, 100, 100, 3)


In [69]:
batch_size=128
epochs=10
num_classes = 120
model=Sequential()
input_shape=X_train.shape[1:]
model.add(Conv2D(32, kernel_size=(5, 5), strides=(1, 1), activation='relu', input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
model.add(Conv2D(64, (5, 5), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2))) 
model.add(Flatten())
model.add(Dense(256, activation='relu')) 
model.add(Dense(num_classes, activation='softmax'))
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_8 (Conv2D)            (None, 96, 96, 32)        2432      
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 48, 48, 32)        0         
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 44, 44, 64)        51264     
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 22, 22, 64)        0         
_________________________________________________________________
flatten_4 (Flatten)          (None, 30976)             0         
_________________________________________________________________
dense_8 (Dense)              (None, 256)               7930112   
_________________________________________________________________
dense_9 (Dense)              (None, 120)              

In [0]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

### Use batch_size = 128 and epochs = 10 and execute the model

In [0]:
batch_size=128
epochs=10

In [73]:
model.fit(X_train,y_train,batch_size=batch_size,epochs=epochs,verbose=1)

Epoch 1/10
64/64 [==============================] - 180s 3s/step - loss: 4.8170 - accuracy: 0.0120
Epoch 2/10
64/64 [==============================] - 180s 3s/step - loss: 4.6581 - accuracy: 0.0271
Epoch 3/10
64/64 [==============================] - 180s 3s/step - loss: 4.1911 - accuracy: 0.0932
Epoch 4/10
64/64 [==============================] - 181s 3s/step - loss: 3.2735 - accuracy: 0.2560
Epoch 5/10
64/64 [==============================] - 181s 3s/step - loss: 1.9414 - accuracy: 0.5376
Epoch 6/10
64/64 [==============================] - 183s 3s/step - loss: 0.8591 - accuracy: 0.7914
Epoch 7/10
64/64 [==============================] - 182s 3s/step - loss: 0.3616 - accuracy: 0.9166
Epoch 8/10
64/64 [==============================] - 183s 3s/step - loss: 0.2235 - accuracy: 0.9538
Epoch 9/10
64/64 [==============================] - 182s 3s/step - loss: 0.1569 - accuracy: 0.9684
Epoch 10/10
64/64 [==============================] - 181s 3s/step - loss: 0.1333 - accuracy: 0.9727


#The model accuracy is very poor !!!!

### Use Data Augmentation in the above model to see if the accuracy improves


In [0]:
train_datagen = ImageDataGenerator(
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    rescale=1./255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest')

In [0]:
test_datagen=ImageDataGenerator(rescale=1./255)

### Using the above objects, create the image generators with variable names `train_generator` and `val_generator`

You need to use train_datagen.flow() and val_datagen.flow()

In [0]:
training_set=train_datagen.flow(X_train,y=y_train,batch_size=32)
testing_set=test_datagen.flow(X_test,y=y_test,batch_size=32)

### Fit the model using fit_generator() using `train_generator` and `val_generator` from the above step with 10 epochs

In [79]:
 history=model.fit_generator(training_set,
                      steps_per_epoch = 16,
                     validation_data = testing_set,
                       validation_steps = 4,
                       epochs = 10,
                       verbose = 1)

Epoch 1/10
16/16 [==============================] - 13s 808ms/step - loss: 4.7806 - accuracy: 0.0156 - val_loss: 4.7863 - val_accuracy: 0.0156
Epoch 2/10
16/16 [==============================] - 13s 810ms/step - loss: 4.7848 - accuracy: 0.0078 - val_loss: 4.7940 - val_accuracy: 0.0000e+00
Epoch 3/10
16/16 [==============================] - 13s 817ms/step - loss: 4.7858 - accuracy: 0.0137 - val_loss: 4.8003 - val_accuracy: 0.0160
Epoch 4/10
16/16 [==============================] - 13s 815ms/step - loss: 4.7854 - accuracy: 0.0059 - val_loss: 4.7903 - val_accuracy: 0.0078
Epoch 5/10
16/16 [==============================] - 13s 817ms/step - loss: 4.7917 - accuracy: 0.0078 - val_loss: 4.7988 - val_accuracy: 0.0078
Epoch 6/10
16/16 [==============================] - 13s 791ms/step - loss: 4.7864 - accuracy: 0.0101 - val_loss: 4.7916 - val_accuracy: 0.0234
Epoch 7/10
16/16 [==============================] - 13s 810ms/step - loss: 4.7842 - accuracy: 0.0059 - val_loss: 4.8138 - val_accuracy: 0.

# Model accuracy is still poor!!!

### Lets use Transfer Learning

Download the vgg wieght file from here : https://github.com/MinerKasch/applied_deep_learning/blob/master/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5

Use the below code to load VGG16 weights trained on ImageNet

In [87]:
from keras.applications.vgg16 import VGG16
model = VGG16()

553467904/553467096 [==============================] - 6s 0us/step


Print the summary of the base_model

### Add the following classification layers to the imported VGG Model <br>
1. Flatten Layer
2. Dense layer with 1024 neurons with activation as Relu
3. Dense layer with 256 neurons with activation as Relu
4. Dense layer with 120 neurons with activation as Softmax

### Make all the layers in the base_model (VGG16) to be non-trainable

### Fit and compile the model with batch_size = 128 and epochs = 10 and execute the model

Try to get training and validation accuracy to be more than 90%